url: "https://quarantinehub.github.io"
baseurl: "/"

# Site settings
title: Quarantine HUB
email: quarantine.hubmx@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
#stack-overflow
people:
- name: José M. Mireles
  pic: JM.png
  position: Co-founder
  social:
    - title: twitter
      url: https://twitter.com/JMireles_
    - title: facebook
      url: #
    - title: linkedin
      url: https://www.linkedin.com/in/josemirelesq/

- name: Denise López
  pic: DENISE LOPEZ.png
  position: Co-founder
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/denise-l%C3%B3pez-garc%C3%ADa-944606129/
    - title: github
      url: https://github.com/Deni-ctrl
    - title: instagram
      url: https://www.instagram.com/denigarcia18/?hl=es-la

- name: Javier Carrillo
  pic: JAVIER CARRILLO.png
  position: Co-founder
  social:
    - title: facebook
      url: www.facebook.com/xoloitzcuintle.wemol
    - title: github
      url: github.com/Javcm

- name: Andrea Monserrat A.
  pic: ANDREA ARREDONDO.png
  position: Community Lead
  social:
    - title: twitter
      url: https://twitter.com/AndreMonserratt
    - title: github
      url: https://github.com/Andrea-Monserrat
    - title: linkedin
      url: https://www.linkedin.com/in/andrea-monserrat/

- name: Jennifer Baez
  pic: JENNIFER BAEZ.png
  position: Community Lead
  social:
    - title: github
      url:  https://github.com/baezjeniffer
    - title: instagram
      url: https://www.instagram.com/jenny_ffera/
    - title: linkedin
      url: https://www.linkedin.com/in/jeniffer-abigail-martínez-baez-00a882187

- name: Bryan D. Juárez
  pic: BRYAN JUAREZ.png
  position: Community Lead
  social:
    - title: twitter
      url: https://twitter.com/BryanDavjk
    - title: github
      url: https://github.com/BDavidJH
    - title: linkedin
      url: https://www.linkedin.com/in/bryan-david-ju%C3%A1rez-hern%C3%A1ndez-a90421110/

- name: Rafael Ortega Ramírez
  pic: RAFA ORTEGA.png
  position: Community Lead
  social:
    - title: github
      url: https://github.com/rafaelortegar
    - title: facebook
      url: https://www.facebook.com/angel.bambucha/
    - title: linkedin
      url: https://www.linkedin.com/in/rafaelortegar/
      
- name: Bruno Camacho
  pic: BRUNO CAMACHO .png
  position: Community Lead
  social:
    - title: facebook
      url: https://www.facebook.com/char.camachordz
    - title: linkedin
      url: https://www.linkedin.com/in/brunocamachordz/
      
- name: Gibrán Garibay
  pic: GIBRAN FREGOSO.png
  position: Co-founder
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Rodolfo Ferro
  pic: FERRO.png
  position: Lead developer
  social:
    - title: twitter
      url: https://twitter.com/FerroRodolfo/
    - title: instagram
      url: https://www.instagram.com/rodo_ferro/
    - title: github
      url: https://github.com/RodolfoFerro/


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/HubQuarantine
  - title: facebook
    url: https://www.facebook.com/Quarantine-HUB-100133491701774/
  - title: youtube
    url: https://www.youtube.com/channel/UCxag4nc2fy-kmjblIK47svg/
  - title: github
    url: http://github.com/QuarantineHUB

# Build settings
markdown: kramdown
permalink: pretty
